const leagueTableData = [
  {
    pos: 1,
    team: "Arsenal",
    mp: 7,
    w: 6,
    d: 1,
    l: 0,
    gd: 15,
    pts: 19,
    form: ["W", "W", "W", "D", "W"],
    change: "same",
  },
  {
    pos: 2,
    team: "Manchester City",
    mp: 7,
    w: 5,
    d: 2,
    l: 0,
    gd: 12,
    pts: 17,
    form: ["W", "D", "W", "W", "D"],
    change: "same",
  },
  {
    pos: 3,
    team: "Liverpool",
    mp: 7,
    w: 5,
    d: 1,
    l: 1,
    gd: 10,
    pts: 16,
    form: ["W", "W", "L", "W", "D"],
    change: "up",
  },
  {
    pos: 4,
    team: "Chelsea",
    mp: 7,
    w: 4,
    d: 2,
    l: 1,
    gd: 7,
    pts: 14,
    form: ["W", "D", "W", "L", "D"],
    change: "up",
  },
  {
    pos: 5,
    team: "Tottenham",
    mp: 7,
    w: 4,
    d: 1,
    l: 2,
    gd: 5,
    pts: 13,
    form: ["W", "L", "W", "D", "W"],
    change: "down",
  },
  {
    pos: 6,
    team: "Aston Villa",
    mp: 7,
    w: 4,
    d: 1,
    l: 2,
    gd: 3,
    pts: 13,
    form: ["W", "W", "L", "D", "L"],
    change: "up",
  },
  {
    pos: 7,
    team: "Newcastle",
    mp: 7,
    w: 3,
    d: 3,
    l: 1,
    gd: 4,
    pts: 12,
    form: ["D", "W", "D", "W", "D"],
    change: "up",
  },
  {
    pos: 8,
    team: "Brighton",
    mp: 7,
    w: 3,
    d: 2,
    l: 2,
    gd: 2,
    pts: 11,
    form: ["W", "D", "L", "W", "D"],
    change: "down",
  },
  {
    pos: 9,
    team: "Manchester Utd",
    mp: 7,
    w: 3,
    d: 2,
    l: 2,
    gd: 1,
    pts: 11,
    form: ["D", "W", "L", "D", "W"],
    change: "up",
  },
  {
    pos: 10,
    team: "Bournemouth",
    mp: 7,
    w: 3,
    d: 1,
    l: 3,
    gd: 0,
    pts: 10,
    form: ["W", "L", "W", "L", "D"],
    change: "down",
  },
  {
    pos: 11,
    team: "Fulham",
    mp: 7,
    w: 2,
    d: 3,
    l: 2,
    gd: 0,
    pts: 9,
    form: ["D", "L", "D", "W", "D"],
    change: "same",
  },
  {
    pos: 12,
    team: "Brentford",
    mp: 7,
    w: 2,
    d: 2,
    l: 3,
    gd: -2,
    pts: 8,
    form: ["L", "D", "W", "L", "D"],
    change: "up",
  },
  {
    pos: 13,
    team: "West Ham",
    mp: 7,
    w: 2,
    d: 2,
    l: 3,
    gd: -3,
    pts: 8,
    form: ["D", "L", "W", "D", "L"],
    change: "down",
  },
  {
    pos: 14,
    team: "Nottingham Forest",
    mp: 7,
    w: 2,
    d: 1,
    l: 4,
    gd: -4,
    pts: 7,
    form: ["L", "W", "L", "D", "L"],
    change: "down",
  },
  {
    pos: 15,
    team: "Crystal Palace",
    mp: 7,
    w: 1,
    d: 3,
    l: 3,
    gd: -3,
    pts: 6,
    form: ["D", "L", "D", "L", "D"],
    change: "same",
  },
  {
    pos: 16,
    team: "Everton",
    mp: 7,
    w: 1,
    d: 3,
    l: 3,
    gd: -5,
    pts: 6,
    form: ["L", "D", "D", "L", "D"],
    change: "down",
  },
  {
    pos: 17,
    team: "Wolves",
    mp: 7,
    w: 1,
    d: 2,
    l: 4,
    gd: -6,
    pts: 5,
    form: ["L", "D", "L", "W", "L"],
    change: "down",
  },
  {
    pos: 18,
    team: "Leicester",
    mp: 7,
    w: 1,
    d: 1,
    l: 5,
    gd: -8,
    pts: 4,
    form: ["L", "L", "D", "L", "W"],
    change: "down",
  },
  {
    pos: 19,
    team: "Ipswich",
    mp: 7,
    w: 0,
    d: 3,
    l: 4,
    gd: -9,
    pts: 3,
    form: ["D", "L", "L", "D", "D"],
    change: "down",
  },
  {
    pos: 20,
    team: "Southampton",
    mp: 7,
    w: 0,
    d: 1,
    l: 6,
    gd: -11,
    pts: 1,
    form: ["L", "L", "L", "D", "L"],
    change: "same",
  },
]

const topScorersData = [
  { name: "Erling Haaland", team: "Manchester City", goals: 11, assists: 1, rating: 9.2 },
  { name: "Bukayo Saka", team: "Arsenal", goals: 9, assists: 4, rating: 8.9 },
  { name: "Mohamed Salah", team: "Liverpool", goals: 8, assists: 5, rating: 9.0 },
  { name: "Cole Palmer", team: "Chelsea", goals: 7, assists: 3, rating: 8.7 },
  { name: "Alexander Isak", team: "Newcastle", goals: 6, assists: 2, rating: 8.5 },
  { name: "Ollie Watkins", team: "Aston Villa", goals: 6, assists: 1, rating: 8.3 },
  { name: "Son Heung-min", team: "Tottenham", goals: 5, assists: 3, rating: 8.4 },
]

const topAssistsData = [
  { name: "Mohamed Salah", team: "Liverpool", goals: 8, assists: 5, rating: 9.0 },
  { name: "Kevin De Bruyne", team: "Manchester City", goals: 2, assists: 5, rating: 8.6 },
  { name: "Bukayo Saka", team: "Arsenal", goals: 9, assists: 4, rating: 8.9 },
  { name: "Martin Ødegaard", team: "Arsenal", goals: 3, assists: 4, rating: 8.5 },
  { name: "Bruno Fernandes", team: "Manchester Utd", goals: 2, assists: 4, rating: 8.1 },
  { name: "Cole Palmer", team: "Chelsea", goals: 7, assists: 3, rating: 8.7 },
  { name: "Son Heung-min", team: "Tottenham", goals: 5, assists: 3, rating: 8.4 },
]

const topRatingsData = [
  { name: "Erling Haaland", team: "Manchester City", goals: 11, assists: 1, rating: 9.2 },
  { name: "Mohamed Salah", team: "Liverpool", goals: 8, assists: 5, rating: 9.0 },
  { name: "Bukayo Saka", team: "Arsenal", goals: 9, assists: 4, rating: 8.9 },
  { name: "Cole Palmer", team: "Chelsea", goals: 7, assists: 3, rating: 8.7 },
  { name: "Kevin De Bruyne", team: "Manchester City", goals: 2, assists: 5, rating: 8.6 },
  { name: "Martin Ødegaard", team: "Arsenal", goals: 3, assists: 4, rating: 8.5 },
  { name: "Alexander Isak", team: "Newcastle", goals: 6, assists: 2, rating: 8.5 },
]

const matchesData = [
  {
    league: "Premier League",
    status: "live",
    homeTeam: "Arsenal",
    awayTeam: "Chelsea",
    homeScore: 2,
    awayScore: 1,
    homeScorers: "Saka 23', Martinelli 67'",
    awayScorers: "Palmer 45'",
    time: "78'",
    venue: "Emirates Stadium",
  },
  {
    league: "Premier League",
    status: "live",
    homeTeam: "Manchester City",
    awayTeam: "Liverpool",
    homeScore: 1,
    awayScore: 1,
    homeScorers: "Haaland 34'",
    awayScorers: "Salah 56'",
    time: "82'",
    venue: "Etihad Stadium",
  },
  {
    league: "Premier League",
    status: "finished",
    homeTeam: "Tottenham",
    awayTeam: "Aston Villa",
    homeScore: 3,
    awayScore: 2,
    homeScorers: "Son 12', 67', Maddison 45'",
    awayScorers: "Watkins 23', Bailey 78'",
    time: "FT",
    venue: "Tottenham Hotspur Stadium",
  },
  {
    league: "Premier League",
    status: "finished",
    homeTeam: "Newcastle",
    awayTeam: "Brighton",
    homeScore: 2,
    awayScore: 2,
    homeScorers: "Isak 34', Gordon 67'",
    awayScorers: "Mitoma 23', Ferguson 89'",
    time: "FT",
    venue: "St James' Park",
  },
  {
    league: "Premier League",
    status: "finished",
    homeTeam: "Manchester Utd",
    awayTeam: "West Ham",
    homeScore: 2,
    awayScore: 1,
    homeScorers: "Rashford 15', Fernandes 67'",
    awayScorers: "Bowen 45'",
    time: "FT",
    venue: "Old Trafford",
  },
  {
    league: "Premier League",
    status: "finished",
    homeTeam: "Bournemouth",
    awayTeam: "Fulham",
    homeScore: 1,
    awayScore: 1,
    homeScorers: "Solanke 56'",
    awayScorers: "Jiménez 34'",
    time: "FT",
    venue: "Vitality Stadium",
  },
  {
    league: "Premier League",
    status: "finished",
    homeTeam: "Brentford",
    awayTeam: "Wolves",
    homeScore: 3,
    awayScore: 1,
    homeScorers: "Toney 12', 45', Mbeumo 78'",
    awayScorers: "Cunha 67'",
    time: "FT",
    venue: "Gtech Community Stadium",
  },
  {
    league: "Premier League",
    status: "finished",
    homeTeam: "Crystal Palace",
    awayTeam: "Everton",
    homeScore: 1,
    awayScore: 1,
    homeScorers: "Eze 23'",
    awayScorers: "Calvert-Lewin 67'",
    time: "FT",
    venue: "Selhurst Park",
  },
]
