const leagueTableData = [
  {
    pos: 1,
    team: "Arsenal",
    mp: 7,
    w: 5,
    d: 1,
    l: 1,
    gd: 11,
    pts: 16,
    form: ["L", "W", "D", "W", "W"],
    change: "up",
  },
  {
    pos: 2,
    team: "Liverpool",
    mp: 7,
    w: 5,
    d: 0,
    l: 2,
    gd: 4,
    pts: 15,
    form: ["W", "W", "W", "L", "L"],
    change: "down",
  },
  {
    pos: 3,
    team: "Tottenham",
    mp: 7,
    w: 4,
    d: 2,
    l: 1,
    gd: 8,
    pts: 14,
    form: ["L", "W", "D", "D", "W"],
    change: "up",
  },
  {
    pos: 4,
    team: "Bournemouth",
    mp: 7,
    w: 4,
    d: 2,
    l: 1,
    gd: 3,
    pts: 14,
    form: ["W", "W", "D", "D", "W"],
    change: "up",
  },
  {
    pos: 5,
    team: "Man City",
    mp: 7,
    w: 4,
    d: 1,
    l: 2,
    gd: 9,
    pts: 13,
    form: ["L", "W", "D", "W", "W"],
    change: "up",
  },
  {
    pos: 6,
    team: "Crystal Palace",
    mp: 7,
    w: 3,
    d: 3,
    l: 1,
    gd: 4,
    pts: 12,
    form: ["W", "D", "W", "W", "L"],
    change: "down",
  },
  {
    pos: 7,
    team: "Chealsea",
    mp: 7,
    w: 3,
    d: 2,
    l: 2,
    gd: 4,
    pts: 11,
    form: ["W", "D", "L", "L", "W"],
    change: "up",
  },
  {
    pos: 8,
    team: "Everton",
    mp: 7,
    w: 3,
    d: 2,
    l: 2,
    gd: 2,
    pts: 11,
    form: ["W", "D", "L", "D", "W"],
    change: "up",
  },
  {
    pos: 9,
    team: "Sunderland",
    mp: 7,
    w: 3,
    d: 2,
    l: 2,
    gd: 1,
    pts: 11,
    form: ["W", "D", "D", "W", "L"],
    change: "down",
  },
  {
    pos: 10,
    team: "Man Utd",
    mp: 7,
    w: 3,
    d: 1,
    l: 3,
    gd: -2,
    pts: 10,
    form: ["W", "L", "W", "L", "W"],
    change: "up",
  },
  {
    pos: 11,
    team: "Newcastle",
    mp: 7,
    w: 2,
    d: 3,
    l: 2,
    gd: 1,
    pts: 9,
    form: ["D", "W", "D", "L", "W"],
    change: "up",
  },
  {
    pos: 12,
    team: "Brighton",
    mp: 7,
    w: 2,
    d: 3,
    l: 2,
    gd: 0,
    pts: 9,
    form: ["W", "L", "D", "W", "D"],
    change: "same",
  },
  {
    pos: 13,
    team: "Aston Villa",
    mp: 7,
    w: 2,
    d: 3,
    l: 2,
    gd: -1,
    pts: 9,
    form: ["L", "D", "D", "W", "W"],
    change: "same",
  },
  {
    pos: 14,
    team: "Fulham",
    mp: 7,
    w: 2,
    d: 2,
    l: 2,
    gd: -3,
    pts: 8,
    form: ["L", "W", "W", "L", "L"],
    change: "down",
  },
  {
    pos: 15,
    team: "Leeds",
    mp: 7,
    w: 2,
    d: 2,
    l: 3,
    gd: -4,
    pts: 8,
    form: ["D", "L", "W", "D", "L"],
    change: "down",
  },
  {
    pos: 16,
    team: "Brentford",
    mp: 7,
    w: 2,
    d: 1,
    l: 4,
    gd: -3,
    pts: 7,
    form: ["L", "D", "L", "W", "L"],
    change: "down",
  },
  {
    pos: 17,
    team: "Forest",
    mp: 7,
    w: 1,
    d: 2,
    l: 4,
    gd: -7,
    pts: 5,
    form: ["L", "L", "D", "L", "L"],
    change: "down",
  },
  {
    pos: 18,
    team: "Burnley",
    mp: 7,
    w: 1,
    d: 1,
    l: 5,
    gd: -8,
    pts: 4,
    form: ["L", "L", "D", "L", "L"],
    change: "same",
  },
  {
    pos: 19,
    team: "West Ham",
    mp: 7,
    w: 1,
    d: 1,
    l: 5,
    gd: -10,
    pts: 4,
    form: ["W", "L", "L", "D", "L"],
    change: "same",
  },
  {
    pos: 20,
    team: "Wolves",
    mp: 7,
    w: 0,
    d: 2,
    l: 5,
    gd: -9,
    pts: 2,
    form: ["L", "L", "L", "D", "D"],
    change: "same",
  },
]

const topScorersData = [
  { name: "Erling Haaland", team: "Manchester City", goals: 9, assists: 1, rating: 8.9 },
  { name: "Antoine Semenyo", team: "Bournemouth", goals: 6, assists: 3, rating: 8.2 },
  { name: "Jaidon Anthony", team: "Burnley", goals: 4, assists: 1, rating: 7.8 },
  { name: "Igor Thiago", team: "Brentford", goals: 4, assists: 0, rating: 7.7 },
  { name: "Mohamed Salah", team: "Liverpool", goals: 2, assists: 2, rating: 8.5 },
  { name: "Bukayo Saka", team: "Arsenal", goals: 3, assists: 2, rating: 8.3 },
  { name: "Cole Palmer", team: "Chelsea", goals: 3, assists: 1, rating: 8.1 },
]

const topAssistsData = [
  { name: "Antoine Semenyo", team: "Bournemouth", goals: 6, assists: 3, rating: 8.2 },
  { name: "Mohamed Salah", team: "Liverpool", goals: 2, assists: 2, rating: 8.5 },
  { name: "Bukayo Saka", team: "Arsenal", goals: 3, assists: 2, rating: 8.3 },
  { name: "Kevin De Bruyne", team: "Manchester City", goals: 1, assists: 2, rating: 8.0 },
  { name: "Bruno Fernandes", team: "Manchester Utd", goals: 1, assists: 2, rating: 7.8 },
  { name: "Erling Haaland", team: "Manchester City", goals: 9, assists: 1, rating: 8.9 },
  { name: "Jaidon Anthony", team: "Burnley", goals: 4, assists: 1, rating: 7.8 },
]

const topRatingsData = [
  { name: "Erling Haaland", team: "Manchester City", goals: 9, assists: 1, rating: 8.9 },
  { name: "Mohamed Salah", team: "Liverpool", goals: 2, assists: 2, rating: 8.5 },
  { name: "Bukayo Saka", team: "Arsenal", goals: 3, assists: 2, rating: 8.3 },
  { name: "Antoine Semenyo", team: "Bournemouth", goals: 6, assists: 3, rating: 8.2 },
  { name: "Cole Palmer", team: "Chelsea", goals: 3, assists: 1, rating: 8.1 },
  { name: "Kevin De Bruyne", team: "Manchester City", goals: 1, assists: 2, rating: 8.0 },
  { name: "Alexander Isak", team: "Newcastle", goals: 2, assists: 1, rating: 7.9 },
]

const matchesData = [
  {
    league: "Premier League",
    status: "finished",
    homeTeam: "Arsenal",
    awayTeam: "West Ham",
    homeScore: 2,
    awayScore: 0,
    homeScorers: "Saka 23', Martinelli 67'",
    awayScorers: "",
    time: "FT",
    venue: "Emirates Stadium",
  },
  {
    league: "Premier League",
    status: "finished",
    homeTeam: "Chelsea",
    awayTeam: "Liverpool",
    homeScore: 2,
    awayScore: 1,
    homeScorers: "Palmer 34', Jackson 67'",
    awayScorers: "Salah 45'",
    time: "FT",
    venue: "Stamford Bridge",
  },
  {
    league: "Premier League",
    status: "finished",
    homeTeam: "Leeds United",
    awayTeam: "Tottenham",
    homeScore: 1,
    awayScore: 2,
    homeScorers: "Bamford 23'",
    awayScorers: "Son 45', Maddison 78'",
    time: "FT",
    venue: "Elland Road",
  },
  {
    league: "Premier League",
    status: "finished",
    homeTeam: "Manchester Utd",
    awayTeam: "Sunderland",
    homeScore: 2,
    awayScore: 0,
    homeScorers: "Rashford 15', Fernandes 67'",
    awayScorers: "",
    time: "FT",
    venue: "Old Trafford",
  },
  {
    league: "Premier League",
    status: "finished",
    homeTeam: "Aston Villa",
    awayTeam: "Burnley",
    homeScore: 2,
    awayScore: 1,
    homeScorers: "Watkins 34', Bailey 78'",
    awayScorers: "Anthony 56'",
    time: "FT",
    venue: "Villa Park",
  },
  {
    league: "Premier League",
    status: "finished",
    homeTeam: "Bournemouth",
    awayTeam: "Fulham",
    homeScore: 3,
    awayScore: 1,
    homeScorers: "Semenyo 12', 45', Solanke 67'",
    awayScorers: "Jiménez 78'",
    time: "FT",
    venue: "Vitality Stadium",
  },
]

window.leagueTableData = leagueTableData
window.topScorersData = topScorersData
window.topAssistsData = topAssistsData
window.topRatingsData = topRatingsData
window.matchesData = matchesData
